module.exports = [
    {
      id: 1,
      name: 'YSL Black Opium Eau de Parfum 50ml',
      image: '/images/YSL_Black_Opium.png',
      description:
        'The original Eau de Parfum. Addictive and energising. A captivating floral gourmand scent, twisted with an overdose of black coffee, for a shot of adrenaline. Energy, sensuality, coupled with that unique YSL edge. The signature black coffee accord is paired with sensual vanilla, enriched by the softness of white flowers and orange blossom, against a base of patchouli and comforting white musk. A daring contrast of light and dark, for a women’s fragrance that bewitches with its trail.',
      brand: 'YSL ',
      category: 'Parfum',
      pricePer100: 131.2,
      price: 65.6,
      countInStock: 10,
      rating: 4.8,
      numReviews: 1200,
    },
    {
      id: 2,
      name: 'DIOR Miss Dior Eau de Parfum 50ml',
      image: '/images/DIOR_Miss_Dior.png',
      description:
        "The new Miss Dior eau de parfum brings in a wave of optimism and brims with life—echoing Miss Dior's very essence. Miss Dior's fresh and floral notes are composed like a bouquet of countless flowers with endless sparkling colours. François Demachy, Perfumer-Creator of the House of Dior, wanted to create an iridescent Rose for this fragrance that is lit up by a myriad of fresh and floral notes.",
      brand: 'DIOR',
      category: 'Parfum',
      pricePer100: 166.0,
      price: 83.0,
      countInStock: 17,
      rating: 4.5,
      numReviews: 80,
    },
    {
      id: 3,
      name: 'Emporio Armani Diamonds Eau de',
      image: '/images/Armani_Diamonds.png',
      description:
        'A fragrance that reflects the sparkle, strength, brilliance and sexiness of the EMPORIO ARMANI woman. The sensory blend is a surprising gourmand fragrance to give a stone a flavor and to a woman a self confident and audacious feeling',
      brand: 'Armani',
      category: 'Parfum',
      pricePer100: 65.0,
      price: 32.5,
      countInStock: 5,
      rating: 4,
      numReviews: 12,
    },
    {
      id: 4,
      name: 'MUGLER Angel Refillable Eau de',
      image: '/images/MUGLER_Angel_Refillable.png',
      description:
        'Angel, the first fragrance by MUGLER, is a voluptuous oriental gourmand, which has a stunning movie star looks too. A collection of truly beautiful bottles resembling dazzling stars cut from a night blue sky',
      brand: 'MUGLER',
      category: 'Parfum',
      pricePer100: 185.6,
      price: 92.8,
      countInStock: 11,
      rating: 4.2,
      numReviews: 32,
    },
    {
      id: 5,
      name: 'Hugo Boss For Him',
      image: '/images/hugo_boss_him.png',
      description:
        'BOSS THE SCENT has been created for BOSS Men who play seduction slowly, passionately and as an experience to be savoured and returned to time after time. With BOSS THE SCENT, he can engage all five senses, tapping into what women really want: An irresistible aftershave, unforgettable like a savoured seduction',
      brand: 'BOSS',
      category: 'Parfum',
      pricePer100: 72.0,
      price: 36.0,
      countInStock: 12,
      rating: 3.9,
      numReviews: 80,
    },
    {
      id: 6,
      name: 'YSL Y Mens Eau de Parfum ',
      image: '/images/ysl_men.png',
      description:
        'Y by Yves Saint Laurent is not the story of one man but of a whole generation: a creative generation of men who dare to follow their passions and carve their own paths. From inspiration, through hard work and collaboration, to self-accomplishment and success.',
      brand: 'YSL',
      category: 'Parfum',
      pricePer100: 72.0,
      price: 52.8,
      countInStock: 0,
      rating: 3.5,
      numReviews: 12,
    },
  ]
  